#pragma once

#include <cstdint>
#include <optional>

// -----------------------------------------------------------------------------
// Simple single-instrument Limit Order Book (LOB).
//
// Defines core data structures used by a matching engine:
//   - Side   : buy/sell indicator
//   - Order  : client-submitted limit/market order
//   - Trade  : execution record
//
// This header contains data definitions only.
// -----------------------------------------------------------------------------

namespace lob {

/**
 * @enum Side
 * @brief Order side (Buy or Sell).
 */
enum class Side {
    Buy,  ///< Buy side
    Sell  ///< Sell side
};

/**
 * @brief Returns the opposite side (Buy <-> Sell).
 *
 * @param s The input side.
 * @return The opposite side.
 */
inline Side opposite(Side s) {
    return (s == Side::Buy) ? Side::Sell : Side::Buy;
}

/**
 * @struct Order
 * @brief Represents a client-submitted order.
 *
 * Limit orders must specify a price.
 * Market orders set `price = std::nullopt`.
 */
struct Order {
    std::int64_t          order_id;   ///< Unique order identifier.
    Side                  side;       ///< Buy or Sell.
    std::optional<double> price;      ///< Limit price; nullopt for market orders.
    std::int64_t          quantity;   ///< Remaining unfilled quantity.
    std::int64_t          timestamp;  ///< Submission timestamp (ns/us).
};

/**
 * @struct Trade
 * @brief Execution record generated by matching two orders.
 *
 * Execution price always follows the resting-order price rule.
 */
struct Trade {
    std::int64_t buy_order_id;   ///< ID of the buy order.
    std::int64_t sell_order_id;  ///< ID of the sell order.
    double       price;          ///< Execution price.
    std::int64_t quantity;       ///< Executed quantity.
    std::int64_t timestamp;      ///< Match timestamp.
};


/**
 * @struct OrderNode
 * @brief Forward declaration for linked-list nodes storing resting orders.
 */
struct OrderNode;


/**
 * @struct PriceLevel
 * @brief FIFO queue of resting orders at a single price level.
 *
 * Implements a doubly linked list (head = oldest order, tail = newest).
 */
struct PriceLevel {
    OrderNode* head = nullptr;  ///< Pointer to the oldest resting order.
    OrderNode* tail = nullptr;  ///< Pointer to the most recent resting order.
};


/**
 * @struct OrderNode
 * @brief Node in the doubly linked list representing a single resting order.
 *
 * Each node stores:
 *  - The order itself
 *  - prev pointer (toward older orders)
 *  - next pointer (toward newer orders)
 *
 * Used to support O(1) insertion and cancellation.
 */
struct OrderNode {
    Order      order;           ///< The resting order stored at this node.
    OrderNode* prev = nullptr;  ///< Previous node in the FIFO queue.
    OrderNode* next = nullptr;  ///< Next node in the FIFO queue.
};


} // namespace lob
