#pragma once

#include <cstdint>
#include <optional>

// -----------------------------------------------------------------------------
// Simple single-instrument Limit Order Book (LOB).
//
// Defines core data structures used by a matching engine:
//   - Side   : buy/sell indicator
//   - Order  : client-submitted limit/market order
//   - Trade  : execution record
//
// This header contains data definitions only.
// -----------------------------------------------------------------------------

namespace lob {

/**
 * @enum Side
 * @brief Order side (Buy or Sell).
 */
enum class Side {
    Buy,  ///< Buy side
    Sell  ///< Sell side
};

/**
 * @brief Returns the opposite side (Buy <-> Sell).
 *
 * @param s The input side.
 * @return The opposite side.
 */
inline Side opposite(Side s) {
    return (s == Side::Buy) ? Side::Sell : Side::Buy;
}

/**
 * @struct Order
 * @brief Represents a client-submitted order.
 *
 * Limit orders must specify a price.
 * Market orders set `price = std::nullopt`.
 */
struct Order {
    std::int64_t          order_id;   ///< Unique order identifier.
    Side                  side;       ///< Buy or Sell.
    std::optional<double> price;      ///< Limit price; nullopt for market orders.
    std::int64_t          quantity;   ///< Remaining unfilled quantity.
    std::int64_t          timestamp;  ///< Submission timestamp (ns/us).
};

/**
 * @struct Trade
 * @brief Execution record generated by matching two orders.
 *
 * Execution price always follows the resting-order price rule.
 */
struct Trade {
    std::int64_t buy_order_id;   ///< ID of the buy order.
    std::int64_t sell_order_id;  ///< ID of the sell order.
    double       price;          ///< Execution price.
    std::int64_t quantity;       ///< Executed quantity.
    std::int64_t timestamp;      ///< Match timestamp.
};

} // namespace lob
